confirm("are you over 18");
alert("we dont really care");
var characterName = prompt('choose a main character of the 3 naruto anime main characters and i mean a MAIN CHARACTER unless you want nothing to happen');
if(characterName == 'sasuke'){
    document.write("<div><img src='sasuke2.PNG' width='10%' height='225px' style='float:left;padding-right:10px'/><p><b>Sasuke Uchiha (うちはサスケ, Uchiha Sasuke) is one of the last surviving members of Konohagakure's Uchiha clan.<br> After his older brother, Itachi, slaughtered their clan, Sasuke made it his mission in life to avenge them by killing Itachi.<br> He is added to Team 7 upon becoming a ninja and, through competition with his rival and best friend, Naruto Uzumaki, Sasuke starts developing his skills.<br> Dissatisfied with his progress, he defects from Konoha so that he can acquire the strength needed to exact his revenge. His years of seeking vengeance and his actions that followed become increasingly demanding, irrational and isolates him from others, leading him to be branded as an international criminal.<br> After learning the truth of his brother's sacrifice, later proving instrumental in ending the Fourth Shinobi World War, and being happily redeemed by Naruto, Sasuke decides to return to Konoha and dedicate his life to help protect the village and its inhabitants, becoming referred to as the 'Supporting Kage' (支う影, Sasaukage, literally meaning: Supporting Shadow).</b></p></div>");
}else if (characterName == 'sakura'){
    document.write("<div><img src='sakura.png' width='10%' height='225px' style='float:left;padding-right:10px'/><p><b> NO ONE REALLY CARES ABOUT HER Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex sed sint voluptas facere alias at accusantium, eos quae, itaque inventore necessitatibus animi perspiciatis vitae autem mollitia non delectus qui! Suscipit.<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit.<br> Ex sed sint voluptas facere alias at accusantium, eos quae, itaque inventore necessitatibus animi perspiciatis vitae autem mollitia non delectus qui! Suscipit.<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit.<br> Ex sed sint voluptas facere alias at accusantium, eos quae, itaque inventore necessitatibus animi perspiciatis vitae autem mollitia non delectus qui! Suscipit.<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit.<br> Ex sed sint voluptas facere alias at accusantium, eos quae, itaque inventore necessitatibus animi perspiciatis vitae autem mollitia non delectus qui! Suscipit.</b></p></div>");
}else if (characterName == 'naruto'){
    document.write("<div><img src='naruto.jpg' width='10%' height='225px' style='float:left;padding-right:10px'/><p><b> Naruto Uzumaki (うずまきナルト, Uzumaki Naruto) is a shinobi of Konohagakure's Uzumaki clan.<br> He became the jinchūriki of the Nine-Tails on the day of his birth — a fate that caused him to be shunned by most of Konoha throughout his childhood.<br> After joining Team Kakashi, Naruto worked hard to gain the village's acknowledgement all the while chasing his dream to become Hokage.<br> In the following years, through many hardships and ordeals, he became a capable ninja regarded as a hero both by the villagers, and soon after, the rest of the world, becoming known as the Hero of the Hidden Leaf (木ノ葉隠れの英雄, Konohagakure no Eiyū, literally meaning: Hero of the Hidden Tree Leaves).<br> He soon proved to be one of the main factors in winning the Fourth Shinobi World War, leading him to achieve his dream and become the village's Seventh Hokage (七代目火影, Nanadaime Hokage, literally meaning: Seventh Fire Shadow).</b></p></div>");
};
